# setup
title: 'The Tasting Plate'
baseurl: /the-tasting-plate
exclude: ['README.md']
timezone: Australia/Sydney
port: 4000


# pagination
paginate: 2
paginate_path: '/eats/page:num/'


# defaults
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      permalink: '/eats/:title'
      layout: "post"
      author: "Tina Mao"


# plugins
gems: [jekyll-paginate]