baseurl: /the-tasting-plate
exclude: ['README.md']
timezone: Australia/Sydney
port: 4000
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/eats/:title"
      layout: "post"
      author: "Tina Mao"